DemoExistingDbMVC/Models/ActorDbContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DemoExistingDbMVC.Models;

public partial class ActorDbContext : DbContext
{
    public ActorDbContext()
    {
    }

    public ActorDbContext(DbContextOptions<ActorDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Actors> Actors { get; set; }

   
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

DemoExistingDbMVC/Models/Actors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DemoExistingDbMVC.Models
{
    public partial class Actors
    {
        [Key]
        public int ActorId { get; set; }
        public bool AcademyWiner { get; set; }
        public int Age { get; set; }
        public string? Name { get; set; }
    }
}

DemoExistingDbMVC/Models/ErrorViewModel.cs
namespace DemoExistingDbMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoExistingDbMVC/Controllers/ActorsController.cs
using DemoExistingDbMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoExistingDbMVC.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ActorDbContext _context;
        public ActorsController(ActorDbContext context)
        {
            _context = context;
        }   

        public IActionResult Index()
        {
            return View(_context.Actors.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Actors actors)
        {
            if (!ModelState.IsValid)
            {
                _context.Actors.Add(actors);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(actors);
        }
    }
}

DemoExistingDbMVC/Controllers/HomeController.cs
using DemoExistingDbMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoExistingDbMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoExistingDbMVC/Views/Actors/Create.cshtml
@model DemoExistingDbMVC.Models.Actors

@{
    ViewBag.Title = "New Actor";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Actors" asp-action="Create" method="post" class="form-horizontal" role="form">
    <form asp-controller="Actors" asp-action="Create" method="post" class="form-horizontal" role="form">
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>

            <!-- Name -->
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <!-- Age -->
            <label asp-for="Age" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <!-- AcademyWinner -->
            <label asp-for="AcademyWiner" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AcademyWiner" class="form-control" />
                <span asp-validation-for="AcademyWiner" class="text-danger"></span>
            </div>
            <!-- Create -->
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</form>

DemoExistingDbMVC/Views/Actors/Index.cshtml
@model IEnumerable<DemoExistingDbMVC.Models.Actors>

@{
    ViewBag.Title = "Actors";
}

<h2>Actors</h2>

<p>
    <a asp-controller="Actors" asp-action="Create">Create New</a>
</p>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Age</th>
        <th>Academy Winner</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ActorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademyWiner)
            </td>
        </tr>
    }
</table>

DemoExistingDbMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoExistingDbMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoExistingDbMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoExistingDbMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoExistingDbMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DemoExistingDbMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>